//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.4.1.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------





export class JwtTokenDto implements IJwtTokenDto {
    jwtToken!: string;

    constructor(data?: IJwtTokenDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.jwtToken = _data["JwtToken"];
        }
    }

    static fromJS(data: any): JwtTokenDto {
        data = typeof data === 'object' ? data : {};
        let result = new JwtTokenDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["JwtToken"] = this.jwtToken;
        return data; 
    }
}

export interface IJwtTokenDto {
    jwtToken: string;
}
