//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.4.4.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------





export class ServerEmailDto implements IServerEmailDto {
    serverEmailAddress!: string;

    constructor(data?: IServerEmailDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.serverEmailAddress = _data["ServerEmailAddress"];
        }
    }

    static fromJS(data: any): ServerEmailDto {
        data = typeof data === 'object' ? data : {};
        let result = new ServerEmailDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ServerEmailAddress"] = this.serverEmailAddress;
        return data; 
    }
}

export interface IServerEmailDto {
    serverEmailAddress: string;
}
