//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.4.4.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------





export class UserDto implements IUserDto {
    userId!: number;
    pocketUsername!: string;
    kindleEmailAddress!: string | undefined;

    constructor(data?: IUserDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userId = _data["UserId"];
            this.pocketUsername = _data["PocketUsername"];
            this.kindleEmailAddress = _data["KindleEmailAddress"];
        }
    }

    static fromJS(data: any): UserDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["UserId"] = this.userId;
        data["PocketUsername"] = this.pocketUsername;
        data["KindleEmailAddress"] = this.kindleEmailAddress;
        return data; 
    }
}

export interface IUserDto {
    userId: number;
    pocketUsername: string;
    kindleEmailAddress: string | undefined;
}
